Gulptask
wojtazzz/jak-to-zrobic-w-js pull request #5
Opened 2019-04-09 15:01 UTC by bartosz84l

2019-04-11 14:44 UTC, wojtazzz requested changes

2019-04-11 14:44 UTC, wojtazzz commented on .gitignore
> +*.html
zadziała ale *.html zignoruje wszystkie pliki HTML a tego nie chcemy

no i zostaje rozkminienie jak ignorować te screenshoty - cały czas są skomitowane. 
Wydaje mi się że musisz je odignorować, skasować i wpuszować zmianę kasowania
dopiero z kolejnym PR dodaj ignore'a na folder screenshots

2019-04-11 14:44 UTC, wojtazzz commented on excercsises/3_synchronization/contact.spec.js
> +		var ec = protractor.ExpectedConditions;
tą zmienną możesz deklarować w BeforeEach albo gdzieś poza funckją testu

2019-04-11 14:44 UTC, wojtazzz commented on excercsises/3_synchronization/contact.spec.js
> +		var message = contactPage.findMessageBy(displayMessage, 'h3');
wyżej masz ładne użycie Page Objectów 

natomiast tutaj: 		
var message = contactPage.findMessageBy(displayMessage, 'h3');
		browser.wait(ec.visibilityOf(message), 15000);

wywołujesz już bezpośrednio metody które powinny być zamknięte w jakieś funcji w odpowiednim Page'u

2019-04-11 14:44 UTC, wojtazzz commented on excercsises/3_synchronization/home.spec.js
> -		browser.wait(EC.visibilityOf(menu), 15000);
To samo, zamnknij kilkanie i pobieranie elementów dropdown'u w funcji należacej do odpowiedniego Page'a

2019-04-11 14:44 UTC, wojtazzz commented on gulpfile.js
> +gulp.task('elo', function () {
yo!

2019-04-11 14:44 UTC, wojtazzz commented on gulpfile.js
> +gulp.task('try', function(){
try ? co to robi?

2019-04-11 14:44 UTC, wojtazzz commented on gulpfile.js
> +    return del.sync('screenshots');
pogooglaj to kasowanie folderów w gulpie jeśli to  nie działa

2019-04-11 14:44 UTC, wojtazzz commented on gulpfile.js
> +    gulp.start('clean');
no spoko, jeśli działa to ok ale to już niepotrzebnie zagmatwane:
nie potrzeba taska before który startuje taska clean :)

2019-04-11 14:44 UTC, wojtazzz commented on gulpfile.js
> +    gulp.start('before','all-tests', 'after', 'jslint');
tutaj sobie nazywaliśmy taski z czapy,
docelowo dbaj żeby nazwy mówiły Ci co się defacto dzieje
clean
all-tests
jslint 
są OK!

before, yo i task są słabe:)

2019-04-12 06:33 UTC, bartosz84l commented on excercsises/3_synchronization/contact.spec.js
> +		var ec = protractor.ExpectedConditions;
ok,

2019-04-12 13:47 UTC, bartosz84l commented on gulpfile.js
> +    gulp.start('clean');
ok poprawione w test1

2019-04-12 13:47 UTC, bartosz84l commented on gulpfile.js
> +    gulp.start('before','all-tests', 'after', 'jslint');
ok poprawione w test1

2019-04-12 13:47 UTC, bartosz84l commented on gulpfile.js
> +gulp.task('try', function(){
ok poprawione w test1

2019-04-12 13:49 UTC, bartosz84l commented on gulpfile.js
> +gulp.task('elo', function () {
ok poprawione

2019-04-12 13:49 UTC, bartosz84l commented on gulpfile.js
> +gulp.task('try', function(){
ok poprawione

2019-04-12 13:52 UTC, bartosz84l commented on gulpfile.js
> +    return del.sync('screenshots');
dziala ta funkcja gdy wykonuje to w gulpie, kasuje poprzednie screenshoty

2019-04-12 13:52 UTC, bartosz84l commented on excercsises/3_synchronization/home.spec.js
> -		browser.wait(EC.visibilityOf(menu), 15000);
ok poprawione w test1

2019-04-12 13:52 UTC, bartosz84l commented on excercsises/3_synchronization/contact.spec.js
> +		var message = contactPage.findMessageBy(displayMessage, 'h3');
ok poprawione w test1

2019-04-15 09:22 UTC, merged