gulp
wojtazzz/jak-to-zrobic-w-js pull request #6
Opened 2019-04-11 09:36 UTC by JaroslawKotus

added gulpfile and small changes in excer.. 1,2,3,4

2019-04-11 14:29 UTC, wojtazzz requested changes

2019-04-11 14:29 UTC, wojtazzz commented on excercsises/3_synchronization/contact.spec.js
> +		var newLocal = 'Your message has been sent.';
const w tym przypadku było lepsze od var - kumasz dlaczego?

2019-04-11 14:29 UTC, wojtazzz commented on gulpfile.js
> +gulp.task("task", async function () {
Wszystko super, zmieniłbym tylko nazwę taska z 'task' na jakąś która coś mówi. Może 'runAllTests' ?

2019-04-11 14:29 UTC, wojtazzz commented on gulpfile.js
> +gulp.task("default", gulp.series(gulp.parallel("before", "test", "lint")));
Tu się nie zgodzę. Tzn jak chcesz mieć w końcu uruchomione taski gulpa - równolegle czy sekwencyjnie??

2019-04-11 14:29 UTC, wojtazzz commented on htmlReport.html
> -<!DOCTYPE html><html><head lang=en><meta charset=UTF-8><title></title><style>body{font-family:"open_sans",sans-serif}.suite{width:100%;overflow:auto}.suite .stats{margin:0;width:90%;padding:0}.suite
dałoby się to wywalić ? :)

2019-04-11 14:29 UTC, wojtazzz commented on excercsises/4_inheritance/pages/page.js
> +// /**
Raczej nie wymagamy nigdy dokumentowania funkcji w ten sposób.

O ile nazwa funkcji jest wystarczająco dobra i wiadomo co robi to unikaj komentarzy. Komentarze prędzej czy późnej się dezaktualizują

2019-04-11 14:29 UTC, wojtazzz commented on excercsises/4_inheritance/pages/contact.js
> +    element(by.id(selector)).sendKeys(txt);
jak mówiłem żeby selectory były w zmiennych to miałem na myśli zrobienie zmiennych dla całej klasy tak jak:
this.menuItems = element.all(by.css('ul.nav > li > a'));

To jest optymalne bo masz nazwę która mówi Ci wyraźnie co to za element na stronie (menu items) i możesz jej użyć wiele razy w wielu funkcjach

2019-04-12 05:56 UTC, JaroslawKotus commented on excercsises/3_synchronization/contact.spec.js
> +		var newLocal = 'Your message has been sent.';
tak znam różnice, zmieniłem to ze względu na to, że js lint mi to podkreślał. zmienię to na const :)

2019-04-12 07:04 UTC, wojtazzz commented on gulpfile.js
> +gulp.task("default", gulp.parallel("before", "test", "lint"));
pudło:D

2019-04-12 07:06 UTC, merged